# Generated by Django 2.2.5 on 2019-10-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(verbose_name='ativar')),
                ('period_to', models.DateField(verbose_name='data de término')),
                ('period_from', models.DateField(verbose_name='data de início')),
                ('time_to', models.TimeField(verbose_name='hora de termino')),
                ('time_from', models.TimeField(verbose_name='hora de início')),
                ('institution', models.CharField(max_length=128, verbose_name='instituição')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('job', models.CharField(max_length=128, verbose_name='cargo')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='telefone')),
                ('doc_type', models.CharField(choices=[('RG', 'RG'), ('CPF', 'CPF'), ('USP', 'USP'), ('Passaporte', 'Passaporte')], max_length=128, verbose_name='tipo documento')),
                ('doc_number', models.CharField(max_length=128, verbose_name='numero do documento')),
                ('answerable', models.CharField(choices=[('Pessoa1', 'Pessoa1'), ('Pessoa2', 'Pessoa2')], max_length=128, verbose_name='responsável')),
                ('observation', models.CharField(max_length=1024, verbose_name='observação')),
            ],
        ),
    ]
