# Generated by Django 2.2.5 on 2019-10-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='status',
            field=models.CharField(blank=True, choices=[('Autorizado', 'Autorizado'), ('Para autorização', 'Para autorização'), ('Não autorizado', 'Não autorizado')], default='Para autorização', max_length=128, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='access',
            name='enable',
            field=models.BooleanField(default=False, verbose_name='ativar'),
        ),
    ]
