# Generated by Django 2.2.5 on 2019-10-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20191003_1838'),
        ('access', '0002_auto_20191003_1954'),
    ]

    operations = [
    ]
