# Generated by Django 2.2.5 on 2019-10-08 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_merge_20191003_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': 'acesso', 'verbose_name_plural': 'acessos'},
        ),
        migrations.AddField(
            model_name='access',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='access',
            name='status',
            field=models.CharField(blank=True, choices=[('Autorizado', 'Autorizado'), ('Para autorização', 'Para autorização'), ('Não autorizado', 'Não autorizado')], default='Para autorização', max_length=128, null=True, verbose_name='status'),
        ),
    ]
