# Generated by Django 2.2.5 on 2019-10-08 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_auto_20191008_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='created_at',
        ),
    ]
