# Generated by Django 2.2.5 on 2019-10-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_access_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='created_at',
        ),
    ]
