# Generated by Django 2.2.5 on 2019-10-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_remove_access_created_at'),
        ('access', '0002_access_created_at'),
    ]

    operations = [
    ]
