# Generated by Django 2.2.5 on 2019-10-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('access', '0008_merge_20191008_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'ordering': ('-created_at',), 'verbose_name': 'acesso', 'verbose_name_plural': 'acessos'},
        ),
        migrations.AddField(
            model_name='access',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='access',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data de criação'),
        ),
    ]
