# Generated by Django 2.2.5 on 2019-10-29 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0009_auto_20191010_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid'),
        ),
    ]
