# Generated by Django 2.2.5 on 2019-11-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0011_auto_20191107_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='status',
            field=models.CharField(blank=True, choices=[('Autorizado', 'Autorizado'), ('Para autorização', 'Para autorização'), ('Não authorizado', 'Não authorizado')], default='Para autorização', max_length=128, null=True, verbose_name='status'),
        ),
    ]
