# Generated by Django 3.0.4 on 2020-03-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0015_auto_20200127_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'ordering': ('-created_at',), 'permissions': [('can_manage_access_status', 'Can manage access status')], 'verbose_name': 'acesso', 'verbose_name_plural': 'acessos'},
        ),
    ]
