# Generated by Django 2.2.5 on 2019-10-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build', models.CharField(max_length=4, verbose_name='build')),
                ('floor', models.CharField(max_length=50, verbose_name='floor')),
                ('local', models.CharField(max_length=128, verbose_name='local')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
        ),
    ]
