# Generated by Django 2.2.5 on 2019-10-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locals', '0002_auto_20191001_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locals',
            name='departament',
            field=models.CharField(choices=[('Astronomia', 'Astronomia'), ('Ciências Atmosféricas', 'Ciências Atmosféricas'), ('Geofísica', 'Geofísica'), ('Informática', 'Informática'), ('Administração', 'Administração'), ('Biblioteca', 'Biblioteca')], max_length=128, verbose_name='Departamento'),
        ),
    ]
